/* ####################################################################### *\
|| #           PONTO DE ENTRADA UTILIZADO PELO IMPORTADOR GATI           # ||
|| #                                                                     # ||
|| #    É EXECUTADO DEPOIS QUE A PRÉ-NOTA É EXCLUÍDA PARA FAZER O XML    # ||
|| #              VOLTAR PARA A TELA INICIAL DO IMPORTADOR               # ||
\* ####################################################################### */

User Function A140EXC()
U_GTPE003()
Return .T.