/* ####################################################################### *\
|| #           PONTO DE ENTRADA UTILIZADO PELO IMPORTADOR GATI           # ||
|| #                                                                     # ||
|| #         FORÇA A INCLUSÃO DA CHAVE NO CONHECIMENTO DE FRETE          # ||
\* ####################################################################### */

User Function MT116GRV()
U_GTPE008()
Return